### ISSUE TITLE
file_cache is unavailable when using oauth2client >= 4.0.0, import issueModuleNotFoundError: No module named 'oauth2client.contrib.locked_file'

### ISSUE THREAD

**Issue by US579** [xflr6/gsheets#13]
any chance can add an option for `cache_discovery=False` in discovery build 
<img width="647" alt="Screen Shot 2020-08-13 at 09 55 33" src="https://user-images.githubusercontent.com/37062041/90079382-21f1c580-dd4b-11ea-93dd-e1b1c0f69c3e.png">

**Comment by xflr6** [comment]
Thanks. Can you check if [this branch](https://github.com/xflr6/gsheets/tree/cache_discovery) would go into the wanted direction?

`file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth`

Is the google-auth part relevant  here?

**Comment by US579** [comment]
No google-auth is not relevant, this should be fine

**Comment by xflr6** [comment]
Fixed in [0.5.1 release](https://pypi.org/project/gsheets/0.5.1/#files).
