### ISSUE TITLE
Any possible to support async?

### ISSUE THREAD

**Issue by w-tim** [xflr6/gsheets#14]
Thanks for your excellent gsheets. I use it to download CSV from google drive frequently.

It will take about 4s to download one piece based on 200kb. Very slow. I am not sure if it was caused by Google API.
Could you support async? Thus, I am download multi pieces simultaneously maybe.

**Comment by xflr6** [comment]
Thanks, glad if it is useful.

Do the spreadsheets have multiple worksheets? IIUC this is about downloading multiple spreadsheets: Are you (re-)using the same `gsheets.Sheets` instance for fetching different spreadsheets?

**Comment by w-tim** [comment]
> Thanks, glad if it is useful.
> 
> Do the spreadsheets have multiple worksheets? IIUC this is about downloading multiple spreadsheets: Are you (re-)using the same `gsheets.Sheets` instance for fetching different spreadsheets?

Hi, 
Yes, multiple worksheets. I didn't realized that actually I can use sheets.get() for one time and then sheets[0], sheets[1] before and asked this async question. (I defined export sheets[0] as one def and export sheets[1] as second def)

```
s = sheets.get()
s.sheets[0].to_csv(file, encoding='utf-8-sig', dialect='excel')
```
 
However now actually I found the majority of time used on "s = sheets.get()" instead of .to_csv progress.

Of course my question is still suitable for downloading worksheets for different workbook simultaneously. If async available, it could be faster I suppose.

**Comment by xflr6** [comment]
When fetching multiple spreadsheets, reusing the `Sheets` instance allows to save requests for re-doing discovery/auth (see debug log messages):

```python
import logging

import gsheets

SHEET_IDS = [...]

logging.basicConfig(format='[%(levelname)s@%(name)s] %(message)s',
                    level=logging.DEBUG)

sheets = gsheets.Sheets.from_files(...)

for s_id in SHEET_IDS:
    s = sheets[s_id]
    ...
```

To export all worksheets of a spreadsheet, you can use [SpreadSheet.to_csv()](https://gsheets.readthedocs.io/en/stable/api.html#gsheets.models.SpreadSheet.to_csv) (see the `make_filename` argument for deriving the file name for the CSV file).

Alternatively you can also loop over the worksheets and use [WorkSheet.to_csv()](https://gsheets.readthedocs.io/en/stable/api.html#gsheets.models.WorkSheet.to_csv):

```python
for ws in s.sheets:
    ws.to_csv()
```

If the client is already authorized, both variants should make one request for discovery, and two requests per spreadsheet for loading (metadata + cell values), which, I think, cannot be reduced further.

Do you get quicker results this way than with your original implementation?

AFAIU support for async (non-blocking) IO would require changes in the underlying `google-api-python-client` (see googleapis/google-api-python-client#360).

**Comment by w-tim** [comment]
I got your point.

Many thanks for explanation and codes. Great job on this project.
