### ISSUE TITLE
Service Account Support

### ISSUE THREAD

**Issue by DrBomb** [xflr6/gsheets#15]
Any way to use this API with a service account? I'd really like to start using this package as I already use plenty of the helpers here on the "official" gsheets api from google. But I haven't been able to figure out how to use the service account credentials provided by google.

**Comment by xflr6** [comment]
Can you try [obtaining the `credentials`](https://developers.google.com/identity/protocols/oauth2/service-account#python) and passing them to [`sheets.Sheets()`](https://gsheets.readthedocs.io/en/stable/api.html#gsheets.Sheets) (might need to [set scopes](https://github.com/xflr6/gsheets/blob/9ee77c2a5f6d3875aa2b40b8f34dc83fb410ad12/gsheets/oauth2.py#L76-L84))?

**Comment by xflr6** [comment]
Closing for now.
