### ISSUE TITLE
Program doesn't work when importing gsheets and compiling with pyinstaller

### ISSUE THREAD

**Issue by Aspect1103** [xflr6/gsheets#16]
So I've just finished creating a program using gsheets and want to compile it to a .exe file using pyinstaller. Turns out the google-api-python-client package is broken and doesn't exactly work.

As referenced in this issue: https://github.com/googleapis/google-api-python-client/issues/876 it could be due to importing apiclient instead of googleapiclient, but I'm not sure.

**Comment by xflr6** [comment]
Sorry to head that. +1 from the discussion in the linked issue this seems to be an *upstream* issue (maybe one of the proposed workarounds works such as pinning `google-api-python-client` to `1.8.0`?). Closing here.
