### ISSUE TITLE
How do you pass on credentials to the function get?

### ISSUE THREAD

**Issue by tommycarstensen** [xflr6/gsheets#18]
How does one pass on credentials to the function `get`?

This fails:
```
credentials = gsheets.get_credentials(scopes=url, secrets='credentials.json')
s = gsheets.Sheets().get(url)
```

With this error code:
`ValueError: need credentials or developer_key`

**Comment by xflr6** [comment]
Hi. Pass them to `Sheets` on creation (`gsheets.Sheets(credentials)`, this way this is only needed once when creating the endpoint instead of repeatedly passing them to all method-calls), see also the [API docs](https://gsheets.readthedocs.io/en/stable/api.html#gsheets.Sheets)

**Comment by xflr6** [comment]
If all you need is to speficy file locations, consider also the alternate [Sheets.from_files()](https://gsheets.readthedocs.io/en/stable/api.html#gsheets.Sheets.from_files) constructor.
