### ISSUE TITLE
Date 2017-07-20 is wrongly parsed as an int

### ISSUE THREAD

**Issue by jups23** [xflr6/gsheets#2]
# What I found

When I retrieve this sheet: 
https://docs.google.com/spreadsheets/d/1amynEZWMSHat2HE6MLOn0pAjGS9-tqiq5sj5D2nrDG0/edit?usp=sharing

Containing this data:

Date | Foobar
------------ | -------------
2017-07-20 | A
2017-07-21 | B

gsheets parses this data:

    >>> w.to_frame()
        Date    Foobar
    0  42936  A
    1  42937  B

My code:

    >>> s = sheets.get('https://docs.google.com/spreadsheets/d/1lgGi_eEsLWLS8DhLCT_2Xxl-UiLAznOnzB9LBTnl8dA/')
    <SpreadSheet 1lgGi...dA u'Untitled spreadsheet'>
    >>> w = s.find('Sheet1')
    <WorkSheet 0 u'Sheet1' (5x2)>
    >>> w['A2']
    42936

# What I expected
I expected these date strings to be parsed as a string or a datetime object.

    >>> w['A2']
    2017-07-20

How can I fix it or is the gsheet parser wrong?

**Comment by xflr6** [comment]
Thanks. With #4, date(time)s are be returned as a string.
In your example, `w.to_frame(parse_dates=['Date'])` should give you the wanted result.
