### ISSUE TITLE
Loading certain sized spreadsheets gives a 403 error

### ISSUE THREAD

**Issue by Zylvian** [xflr6/gsheets#6]
Traceback:

```
Traceback (most recent call last):
  File "C:/CODE FOLDER/Google Sheets/gsheets_grading_script.py", line 72, in <module>
    main()
  File "C:/CODE FOLDER/Google Sheets/gsheets_grading_script.py", line 11, in main
    spreadsheet = sheets.get('https://docs.google.com/spreadsheets/d/1ptJ7vHTFzsrHoL5ZsVB6D7FbZccL8K8Ob28xQ0XvYZc/edit')
  File "C:\CODE FOLDER\Google Sheets\venv\lib\site-packages\gsheets\api.py", line 107, in get
    return self[id]
  File "C:\CODE FOLDER\Google Sheets\venv\lib\site-packages\gsheets\api.py", line 88, in __getitem__
    result = models.SpreadSheet._from_response(response, self._sheets)
  File "C:\CODE FOLDER\Google Sheets\venv\lib\site-packages\gsheets\models.py", line 19, in _from_response
    values = backend.values(service, id, ranges)
  File "C:\CODE FOLDER\Google Sheets\venv\lib\site-packages\gsheets\backend.py", line 68, in values
    response = service.spreadsheets().values().batchGet(**params).execute()
  File "C:\CODE FOLDER\Google Sheets\venv\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\CODE FOLDER\Google Sheets\venv\lib\site-packages\googleapiclient\http.py", line 851, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://sheets.googleapis.com/v4/spreadsheets/**long ass link** returned "Range ('('gas007'!GAS7)) exceeds grid limits. Max rows: 1001, max columns: 27">
```

The link results in this:
https://i.gyazo.com/8345e5a5d26d72dad3ca10a0bf3a79d6.png

I have tried editing the scopes, and even with the so called "admin" scopes it still gives me this error.

This spreadsheet has about 20 sheets, but the sheets are 80x8 at max. The `Max rows: 1001, max columns: 27` changes whenever I edit rows, so it's somehow a counter of the rows.

I even tried copying the first sheet, the "('gas007'!GAS7)" one into a seperate spreadsheet, and it parsed just fine. 

I'm curious if it has anything to do with the deprecation of OAuth.

---

# To replicate:

Try and do `.get(https://docs.google.com/spreadsheets/d/1ptJ7vHTFzsrHoL5ZsVB6D7FbZccL8K8Ob28xQ0XvYZc/edit#gid=1686701513)`.
This fails for some reason.

Then do `.get(https://docs.google.com/spreadsheets/d/1ey4cHVM0HvYZtC4UOoV1DwzZjR-YH6EkUpiHfVQoLvw/edit#gid=0)` and it goes through.

The second spreadsheet is actually seriously a copy of the first one, I even used Google's built in tools. But the last one doesn't work.

**Comment by Zylvian** [comment]
I want to add however that this is by far the best wrapper for the Google Sheets API.

After failing with this one, I ended up going through this Google's raw API, gspread and pygsheets, and they all had worse way of doing stuff that this project has gotten down.

Notably, I ended up having to download and export the sheet as a .csv using pygsheets, but because it had no options for dialect nor encoding, I had to make a seperate function that re-opened the file and replaced all commas with excel tabs, and encoded with utf-16.

So I can't wait for this problem to be resolved haha

**Comment by xflr6** [comment]
Thanks for the detailed report (and sorry for the late response).

> This spreadsheet has about 20 sheets, but the sheets are 80x8 at max.
> The `Max rows: 1001, max columns: 27` changes whenever I edit rows

IIUC loading the two sheets you link to goes over the current API limit for [values.batchGet](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.values/batchGet) (assuming it is 1000 rows and 26 columns, i.e. column `A` to `Z`).

Currently we are loading all worksheets in one batch request (requesting one `range` per worksheet). This fails for the `haa037` worksheet in [1ptJ7vHTFzsrHoL5ZsVB6D7FbZccL8K8Ob28xQ0XvYZc](https://docs.google.com/spreadsheets/d/1ptJ7vHTFzsrHoL5ZsVB6D7FbZccL8K8Ob28xQ0XvYZc) (which has 1070 rows and 28 columns) and for the `TEMPLATE` worksheet in [1ey4cHVM0HvYZtC4UOoV1DwzZjR-YH6EkUpiHfVQoLvw](https://docs.google.com/spreadsheets/d/1ey4cHVM0HvYZtC4UOoV1DwzZjR-YH6EkUpiHfVQoLvw) (which has 1027 rows and 28 columns).

Can you try if deleting empty trailing rows/columns from the worksheets or copying the wanted 80x8 area into a new worksheet replacing the old one helps to work around this?

Will investigate more into the API limits, probably need to break loading down into smaller requests where needed.

**Comment by xflr6** [comment]
Closing stale issue (inable to reproduce).
