### ISSUE TITLE
Using .to_csv on a spreadsheet with floats turns the values into dates.

### ISSUE THREAD

**Issue by Zylvian** [xflr6/gsheets#7]
Value in Google Spreadsheet:

https://i.gyazo.com/c437ad1a3117bea98f0f87822ee147e3.png

Value in .csv file:
https://i.gyazo.com/243623e7899ee3334d02e4f5ebee699d.png

(03. mai = 3rd of May in Norwegian)

The code:
```
    for i, sheet in enumerate(spreadsheet.sheets):

        # SHEET STUFF
        student_id = sheet['D2']
        print(student_id)

        sheet.to_csv('grades/' + student_id + '.csv', encoding='utf-16', dialect='excel-tab')
```

**Comment by xflr6** [comment]
Thanks. AFAICT this is due automatic data type recognition in Google Sheets (i.e. not from this library): When entering `3.5` in a new cell, the value is automatically recognized as a date. After correcting the type in the worksheet itself (Format > Number > Number), I think you should get the expected result.

See also https://support.google.com/docs/answer/56470 and https://blog.sheetgo.com/google-sheets-features/google-sheets-data-formats-guide/ (and note that results may be different depending on locale settings).
