### ISSUE TITLE
to_csv doesn't download all rows

### ISSUE THREAD

**Issue by tulsmith** [xflr6/gsheets#8]
No error was thrown.  269 of 399 rows were downloaded. Code is right out of the example at https://pypi.org/project/gsheets/:

     s.sheets[0].to_csv('members.csv', encoding='utf-8', dialect='excel')

The workbook contains multiple sheets.  I haven't tried deleting all the other sheets (have to go through the OAuth pain), so that could be it (although the 4 other sheets are small).  There is one cross-page link from the sheet I want to another sheet.

Is there a way I can get the second half (specify a row range)?

**Comment by tulsmith** [comment]
I created a single sheet workbook. Results were identical. I am having better luck with pygsheets so won't be pursuing this further.

**Comment by xflr6** [comment]
Thanks. Can you maybe provide a minimal reproducible example or share a workbook with some (e.g. dummy) data that allows to reproduce this?

**Comment by xflr6** [comment]
Closing as not reproducible for now.
